import { Anek_Devanagari, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";

const inter = Inter({ subsets: ["latin"] });
const aneka = Anek_Devanagari({ subsets: ["devanagari"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aneka.className}>
        <Navbar />
        {children}</body>
    </html>
  );
}
